### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by debkh** [anshulk/quick-docs#1]
[Enter steps to reproduce below:]
1. Only used default keystroke ctrl-shift-q

**Atom Version**: 1.0.5
**System**: Mac OS X 10.11
**Thrown From**: [quick-docs](https://github.com/anshulk/quick-docs) package, v0.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'message' of null

```
At /Users/BadWolf/.atom/packages/quick-docs/lib/quick-docs.coffee:47

TypeError: Cannot read property 'message' of null
  at Object.module.exports.get_info (/Users/BadWolf/.atom/packages/quick-docs/lib/quick-docs.coffee:47:57)
  at Object.module.exports.toggle (/Users/BadWolf/.atom/packages/quick-docs/lib/quick-docs.coffee:40:14)
  at atom-text-editor.atom.commands.add.quick-docs:toggle (/Users/BadWolf/.atom/packages/quick-docs/lib/quick-docs.coffee:15:12)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/BadWolf/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/BadWolf/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/BadWolf/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/BadWolf/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/BadWolf/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -3:23.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -3:22.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:21.4.0 core:close (atom-text-editor.editor.mini.is-focused)
     -3:16.3.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -3:10.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:58.4.0 core:close (atom-text-editor.editor.mini.is-focused)
     -1:49.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -1:17.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:13.5.0 core:close (div.markdown-preview.native-key-bindings)
  2x -1:11.9.0 core:select-all (div.settings-view.pane-item)
  8x -1:08.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:close (table.package-keymap-table.table.native-key-bindings.text)
     -0:01.5.0 quick-docs:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.11
editor-stats, v0.17.0
emmet, v2.3.12
file-icons, v1.4.0
quick-docs, v0.0.3
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by anshulk** [comment]
Hi @debkh , thanks for trying out  quick-docs and reporting the issue. 

This package depends on [inline-messenger](http://atom.io/packages/inline-messenger). I guess its not clear enough in the description.

Do install it and give quick-docs a try.
